# Generated by Django 4.2.30 on 2026-07-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalflow',
            name='is_user_managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalapprovalflow',
            name='is_user_managed',
            field=models.BooleanField(default=False),
        ),
    ]
